### ISSUE TITLE
Passcode not working

### ISSUE THREAD

**Issue by AmyGrrl** [feudalnate/Original-Xbox-LIVE-Account#1]
I can make an xbox live account just fine with the tool. I can save it to my official 8MB Memory Card. I can then load PSO, select the account and log into play. Now if I use the tool and open the device to edit the live account and set a passcode then save it back to the memory card. Then I load PSO and try to log in. It says the passcode is invalid. If I reopen the live account in the tool, the passcode is still what I set it to. If I remove the passcode and save it back to the memory card. I can then log into PSO just fine. I even tried to format the memory card and make a new live account with a passcode. It still fails. Am I doing something wrong or this a problem with the tool? Thanks!

**Comment by feudalnate** [comment]
This was an issue with incorrect passcode button values. I've troubleshooted the problem and resolved it, correcting the button values in the project and documentation. I pushed the changes and fixed executable to the GitHub project. After re-downloading the executable it should work as expected

Thanks for reporting the issue, I'll leave this open for a few days in case you run into other issues

**Comment by CodeAsm** [comment]
I just saw on AG that I listed A and B as possible passcode entries...very unlikely. My only 2 accounts I think used the triggers and XY, or 4 times 1 button. a too small sample back then.

**Comment by AmyGrrl** [comment]
Thanks! I was able to set a passcode and it worked!

**Comment by feudalnate** [comment]
> I just saw on AG that I listed A and B as possible passcode entries...very unlikely. My only 2 accounts I think used the triggers and XY, or 4 times 1 button. a too small sample back then.

XboxDev has the same button values listed on their wiki for parental controls - I used what information I could find to piece together the button values and it makes sense to assume all button combination passcode prompts would use similar input values since it's such a basic system but games reserving A, B, and LS to allow users to escape the passcode prompts while in-game also makes sense. Either way the values are correct now and I'm not faulting anyone for early research, I should've tested all  the button values were correct instead of assuming
